export const GET_PROPIERTIES = 'GET_PROPIERTIES';
export const FAV_USER_PROPIERTIES = 'FAV_USER_PROPIERTIES';
export const FILTER_PROPIERTIES = 'FILTER_PROPIERTIES';
export const CITY_PROPIERTIES = 'CITY_PROPIERTIES';
